# Generated by Django 5.2.5 on 2025-08-08 05:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('verified_at', models.DateTimeField()),
                ('vc_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('credential_subject', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Verification Log',
                'verbose_name_plural': 'Verification Logs',
                'ordering': ['-verified_at'],
            },
        ),
    ]
