# Generated by Django 5.2.5 on 2025-09-11 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='organization.organization'),
        ),
        migrations.CreateModel(
            name='JsonLdContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('document', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'JSON-LD Context',
                'verbose_name_plural': 'JSON-LD Contexts',
                'indexes': [models.Index(fields=['url'], name='idx_ctx_url')],
            },
        ),
    ]
