# Generated by Django 5.2.6 on 2025-09-18 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_verificationlog_organization_jsonldcontext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationlog",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who performed this verification",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
