# Generated by Django 5.2.6 on 2025-09-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_verified_by_to_verification_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JsonLdContext',
        ),
    ]
