# Generated by Django 5.2.6 on 2025-12-30 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_delete_jsonldcontext"),
        ("openid4vp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationlog",
            name="openid4vp_session",
            field=models.ForeignKey(
                blank=True,
                help_text="OpenID4VP session associated with this verification (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verification_logs",
                to="openid4vp.openid4vpsession",
            ),
        ),
        migrations.AddField(
            model_name="verificationlog",
            name="verification_method",
            field=models.CharField(
                choices=[("offline_qr", "Offline QR"), ("openid4vp", "OpenID4VP")],
                default="offline_qr",
                help_text="Method used for credential verification",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="verificationlog",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("EXPIRED", "Expired"),
                    ("REVOKED", "Revoked"),
                    ("SUSPENDED", "Suspended"),
                ],
                max_length=10,
            ),
        ),
    ]
