# Generated by Django 5.2.5 on 2025-09-06 18:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_organization_did"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationDID",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("did", models.CharField(max_length=500, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("RESOLVED", "Resolved"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dids",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["did"], name="idx_orgdid_did"),
                    models.Index(fields=["organization"], name="idx_orgdid_org"),
                    models.Index(fields=["status"], name="idx_orgdid_status"),
                ],
                "unique_together": {("organization", "did")},
            },
        ),
        migrations.CreateModel(
            name="PublicKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_id", models.CharField(max_length=500, unique=True)),
                ("key_type", models.CharField(max_length=100)),
                ("public_key_multibase", models.TextField()),
                ("public_key_hex", models.TextField(blank=True, null=True)),
                ("public_key_jwk", models.JSONField(blank=True, null=True)),
                ("controller", models.CharField(max_length=500)),
                ("purpose", models.CharField(default="assertion", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_keys",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["organization"], name="idx_pk_org"),
                    models.Index(fields=["key_id"], name="idx_pk_keyid"),
                    models.Index(fields=["controller"], name="idx_pk_controller"),
                    models.Index(
                        fields=["is_active", "revoked_at", "expires_at"],
                        name="idx_pk_active",
                    ),
                ],
            },
        ),
    ]
