# Generated by Django 5.2.6 on 2025-09-10 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emaillogincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrganizationRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255)),
                ('admin_username', models.CharField(max_length=150)),
                ('admin_email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=256)),
                ('otp_code', models.CharField(max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['org_name'], name='idx_pending_org_name'), models.Index(fields=['admin_username'], name='idx_pending_admin_user'), models.Index(fields=['admin_email'], name='idx_pending_admin_email'), models.Index(fields=['expires_at'], name='idx_pending_expires')],
            },
        ),
    ]
