# Generated by Django 5.2.6 on 2025-09-20 18:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonLdContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('document', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='organization.organization')),
            ],
            options={
                'verbose_name': 'JSON-LD Context',
                'verbose_name_plural': 'JSON-LD Contexts',
                'indexes': [models.Index(fields=['organization'], name='idx_ctx_org'), models.Index(fields=['url'], name='idx_ctx_url')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'url'), name='uniq_ctx_org_url')],
            },
        ),
    ]
