# Generated by Django 5.2.6 on 2025-09-22 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_jsonldcontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedVC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vc_id', models.CharField(help_text='Verifiable Credential ID (from credential.id)', max_length=1000)),
                ('issuer', models.CharField(help_text='Issuer DID', max_length=500)),
                ('subject', models.CharField(blank=True, help_text='Subject DID (if available)', max_length=500, null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for revocation', max_length=255, null=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True, help_text='When the VC was marked as revoked')),
                ('metadata', models.JSONField(blank=True, help_text='Additional revocation metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revoked_vcs', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Revoked Verifiable Credential',
                'verbose_name_plural': 'Revoked Verifiable Credentials',
                'indexes': [models.Index(fields=['organization'], name='idx_revokedvc_org'), models.Index(fields=['vc_id'], name='idx_revokedvc_id'), models.Index(fields=['issuer'], name='idx_revokedvc_issuer'), models.Index(fields=['subject'], name='idx_revokedvc_subject')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'vc_id'), name='uniq_revokedvc_org_id')],
            },
        ),
    ]
