# Generated by Django 5.2.6 on 2025-10-01 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_statuslistcredential_replace_revokedvc'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusListCredentialHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_list_id', models.CharField(max_length=1000)),
                ('purposes', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField()),
                ('issuance_date', models.DateTimeField(blank=True, null=True)),
                ('encoded_list_hash', models.CharField(blank=True, max_length=128)),
                ('full_credential', models.JSONField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='statuslistcredential',
            name='idx_statuslist_purpose',
        ),
        migrations.RemoveField(
            model_name='statuslistcredential',
            name='status_purpose',
        ),
        migrations.AddField(
            model_name='statuslistcredential',
            name='encoded_list_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of credentialSubject.encodedList for change detection', max_length=128),
        ),
        migrations.AddField(
            model_name='statuslistcredential',
            name='issuance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statuslistcredential',
            name='purposes',
            field=models.JSONField(default=list, help_text='One or more status purposes'),
        ),
        migrations.AddField(
            model_name='statuslistcredential',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='statuslistcredential',
            name='full_credential',
            field=models.JSONField(help_text='Complete StatusList credential JSON document (latest)'),
        ),
        migrations.AlterField(
            model_name='statuslistcredential',
            name='status_list_id',
            field=models.CharField(help_text='Stable StatusList credential identifier (credential.id)', max_length=1000),
        ),
        migrations.AddIndex(
            model_name='statuslistcredential',
            index=models.Index(fields=['updated_at'], name='idx_statuslist_updated'),
        ),
        migrations.AddField(
            model_name='statuslistcredentialhistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='statuslistcredentialhistory',
            name='status_list_current',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='organization.statuslistcredential'),
        ),
        migrations.AddIndex(
            model_name='statuslistcredentialhistory',
            index=models.Index(fields=['organization'], name='idx_statuslisthist_org'),
        ),
        migrations.AddIndex(
            model_name='statuslistcredentialhistory',
            index=models.Index(fields=['status_list_id'], name='idx_statuslisthist_id'),
        ),
        migrations.AddIndex(
            model_name='statuslistcredentialhistory',
            index=models.Index(fields=['version'], name='idx_statuslisthist_version'),
        ),
        migrations.AddIndex(
            model_name='statuslistcredentialhistory',
            index=models.Index(fields=['archived_at'], name='idx_statuslisthist_archived'),
        ),
        migrations.AlterUniqueTogether(
            name='statuslistcredentialhistory',
            unique_together={('status_list_current', 'version')},
        ),
    ]
