# Generated by Django 5.2.6 on 2025-10-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_statuslistcredentialhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslistcredentialhistory',
            name='issuer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='statuslistcredential',
            name='purposes',
            field=models.JSONField(default=list, help_text='One or more status purposes (list of strings)'),
        ),
    ]
