# Generated by Django 5.2.6 on 2025-12-30 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0007_statuslistcredentialhistory_issuer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenID4VPSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique session identifier for OpenID4VP verification",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "presentation_definition_id",
                    models.CharField(
                        help_text="ID of the presentation definition used for this session",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        help_text="Current status of the verification session",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the session was created"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the session expires"),
                ),
                (
                    "verification_result",
                    models.JSONField(
                        blank=True,
                        help_text="Verification result data (populated after verification)",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if verification failed",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Worker who initiated the verification session",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that initiated the verification",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenID4VP Session",
                "verbose_name_plural": "OpenID4VP Sessions",
                "db_table": "openid4vp_sessions",
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="openid4vp_s_status_ba782c_idx",
                    ),
                    models.Index(
                        fields=["organization", "created_at"],
                        name="openid4vp_s_organiz_5f3a5e_idx",
                    ),
                ],
            },
        ),
    ]
